---
sidebar: sidebar 
permalink: concept_adm_upgrading_nodes.html 
keywords: administer, administering, web, upgrading nodes 
summary: 部署 ONTAP Select 集群后，可以根据需要使用标准 ONTAP 软件升级过程升级每个节点的 ONTAP 映像。 
---
= 升级 ONTAP Select 节点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
部署 ONTAP Select 集群后，您可以根据需要升级集群中每个节点的 ONTAP 映像。


CAUTION: 您不能使用 Deploy 管理实用程序执行现有 ONTAP Select 节点的升级。Deploy 实用程序只能用于创建新的 ONTAP Select 集群。



[[general-procedure]]
== 一般程序

在高级别上，您应该使用以下步骤来升级现有的 ONTAP Select 节点。

.步骤
. 访问 link:https://mysupport.netapp.com/site/downloads/["NetApp 支持站点下载"^] 页面。
. 向下滚动并选择 *ONTAP Select Image*。
. 选择所需的安装映像版本。
. 查看最终用户许可协议 (EULA) 并选择 *Accept & Continue*。
. 选择并下载相应的 *ONTAP Select Image Upgrade* 软件包。根据需要回复所有提示。
+
在升级 ONTAP Select 节点之前，请查看link:reference_release_notes.html["发行说明"]以了解其他信息和任何必需的步骤。

. 使用标准 ONTAP 升级程序和 ONTAP Select 升级文件升级 ONTAP Select 节点。有关支持的升级路径的信息，请参见 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html["支持的 ONTAP 升级路径"^]。




[[revert-an-ontap-select-node]]
== 还原 ONTAP Select 节点

您无法将 ONTAP Select 节点还原为最初安装节点之前的版本。例如：

ONTAP Select 9.16.1 最初已安装:: 您可以将节点升级到版本 9.17.1，然后根据需要恢复到版本 9.16.1。
ONTAP Select 9.17.1 最初已安装:: 无法还原，因为以前未安装早期版本。




[[use-the-vmxnet3-network-driver]]
== 使用 VMXNET3 网络驱动程序

VMXNET3 是 VMware ESXi 上的新集群部署中包含的默认网络驱动程序。如果升级运行 ONTAP Select 9.4 或更早版本的现有 ONTAP Select 节点，则不会自动升级网络驱动程序。您必须手动升级到 VMXNET3。您应该联系 NetApp 支持人员以获得升级方面的帮助。

.相关信息
link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP 升级概述"^]
