---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 您可以在三个平台容量级别之一中购买 ONTAP Select Capacity Tier 或 Capacity Pool 许可证。这些许可证产品决定了部署 ONTAP Select 的主机的功能。 
---
= 了解 ONTAP Select 的平台许可证产品
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以购买标准、高级或高级 XL 级别的 ONTAP Select Capacity Tier 或 Capacity Pool 许可证。这些许可证产品决定了部署 ONTAP Select 的主机的功能。



[[what-a-platform-license-offering-provides]]
== 平台许可证产品提供什么

特定的许可证产品决定了虚拟机监控程序主机在以下两个方面的功能：

* 实例类型（CPU、内存）
* 其他功能


许可证产品按从标准到高级 XL 的功能升序排列。一般来说，您选择的许可证选项授予您该级别和所有较低级别的功能。例如，高级级别提供了高级和标准的功能。

下表比较了标准、高级和高级 XL 许可证产品的功能。

[cols="25,25,25,25,25"]
|===
2+| 许可证支持 ... | 标准 | 高级 | 高级 XL 


2+| 实例类型 | 仅限小型 | 小型或中型 | 小、中或大 


.2+| 硬盘驱动器 (HDD) 在... | 硬件 RAID 配置 | 是 | 是 | 是 


| vNAS 配置 | 是 | 是 | 是 


.3+| 固态硬盘 (SSD) 在... | 硬件 RAID 配置 | 否 | 是 | 是 


| 软件 RAID 配置 | 否 | 是 | 是 


| vNAS 配置 | 是 | 是 | 是 


.3+| NVMe 驱动器在... | 硬件 RAID 配置 | 否 | 否 | 是 


| 软件 RAID 配置 | 否 | 否 | 是 


| vNAS 配置 | 是 | 是 | 是 


2+| MetroCluster SDS | 否 | 是 | 是 
|===

NOTE: 基于内核的虚拟机 (KVM) 不支持大型实例类型。



[[compare-hardware-support-for-platform-license-offerings]]
== 比较平台许可证产品的硬件支持

标准、高级和高级 XL 许可证产品支持各种硬件和软件。有关硬件和软件版本的最新信息，请参见link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]。

[role="tabbed-block"]
====
.核心项
--
[cols="5"30"]
|===


2+| 核心项目类型 3+| 问题描述 


2+| 主机协议 3+| NFS、SMB/CIFS、iSCSI 和 NVMe over TCP 


2+| 部署选项 3+| 单节点 双节点群集（HA 对）四个、六个、八个、十个或十二个节点群集 


2+| 支持的容量（每个节点） 3+| 高达 400TB 原始数据（ESXi 和 KVM） 
|===
--
.硬件
--
[cols="5"30"]
|===


2+| 硬件类型 3+| 问题描述 


2+| 实例大小 | 小型 | 中 | 大型 


2+| CPU 系列 | Intel Xeon E5-26xx v3 (Haswell) 或更高版本 | Intel Xeon E5-26xx v3 (Haswell) 或更高版本 | Intel Xeon E5-26xx v3 (Haswell) 或更高版本 


2+| ONTAP Select CPU / 内存 | 4 个虚拟 CPU (vCPU) / 16GB RAM | 8 个 vCPU / 64GB RAM | 16 个 vCPU / 128GB RAM 


2+| 主机 CPU / 内存最低要求 ^1^ | 6 核 / 24GB 内存 | 10 核 / 72GB 内存 | 18 核 / 136GB 内存 


2+| 网络（每个节点） 3+| 单节点集群最少两个 1GbE 端口 双节点集群（HA 对）最少四个 1GbE 端口 四个、六个、八个、十个或十二个节点集群最少两个 10GbE 端口 
|===
^1^ 假设虚拟机监控程序具有两个内核和 8GB RAM。

--
.存储类型
--
下表提供了指定存储所需的最低许可证类型。 

[cols="5"30"]
|===


2+| 存储类型 3+| 问题描述 


2+| 许可证类型 | 标准 | 高级 | 高级 XL 


2+| 实例大小 | 小型 | 中小型 | 小、中、大 


2+| 带硬件 RAID 控制器的本地 DAS | 8 - 60 个驱动器 | 8 - 60 个驱动器 | 8 - 60 个驱动器 


2+| HDD（SAS、NL-SAS、SATA） | 不适用 | 4 – 60 个驱动器 | 4 – 60 个驱动器 


2+| SSD（SAS） | 不适用 | 4 – 60 个驱动器（仅限 SSD） | 4 – 60 个驱动器（仅限 SSD） 


2+| 使用软件 RAID 的本地 DAS | 不适用 | 适用 | 4 - 14 个驱动器（仅限 NVMe） 


2+| 外部阵列^1^ 3+| 外部阵列上托管的数据存储通过 FC、FCoE、iSCSI 和 NFS 连接（KVM 不支持 NFS）。这些数据存储提供高可用性和弹性。 
|===
^1^ 外部阵列协议支持反映了网络存储连接。

--
.软件
--
[cols="5"30"]
|===


2+| 软件类型 3+| 问题描述 


2+| 虚拟机监控程序支持 (VMware) 3+| VMware vSphere 9.0 VMware vSphere 8.0GA 和更新 1 至 3 VMware vSphere 7.0GA 和更新 1 至 3C 


2+| 虚拟机管理程序支持 (KVM)  a| 
Red Hat Enterprise Linux 64 位 (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7 和 8.6

Rocky Linux (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7 和 8.6



2+| 管理软件 3+| NetApp Active IQ Unified Manager 管理套件 ONTAP Select Deploy Utility SnapCenter（可选） 
|===
--
====
.下一步是什么？
link:concept_lic_workflow.html["了解有关购买 ONTAP Select 许可证的信息"]
