---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: 创建 ONTAP Select 集群后，可以通过执行各种管理任务来支持部署。有几个一般注意事项需要注意。 
---
= 在您开始管理 ONTAP Select 之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
创建 ONTAP Select 集群后，可以通过执行各种管理任务来支持部署。有几个一般注意事项需要注意。

一般来说，可以使用 Deploy Web 界面执行的过程分为三类。

.部署 ONTAP Select 集群
您可以部署单节点或多节点群集。有关详细信息，请参见 link:task_deploy_cluster.html["部署 ONTAP Select 集群"]。

.使用现有的 ONTAP Select 集群执行过程
管理程序分为各种类别，例如 _Security_ 和 _Clusters_。

.在 Deploy 实用程序上执行过程
有几个特定于 Deploy 的过程（例如更改管理员的密码）。



== 管理 ONTAP Select

作为支持 ONTAP Select 的一部分，有许多不同的管理程序可用。此外，还有特定于 Deploy 管理实用程序的程序。以下是其中最重要的程序。一般来说，都使用 Deploy Web 用户界面。


NOTE: 您也可以link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["使用命令行界面"]管理 ONTAP Select。



== 执行其他 ONTAP 配置

部署 ONTAP Select 集群后，您可以像配置和管理基于硬件的 ONTAP 系统一样配置和管理集群。例如，您可以使用 ONTAP System Manager 或 ONTAP CLI 配置 ONTAP Select 集群。

.NetApp 客户端软件
您可以使用以下受支持的 NetApp 客户端软件连接到 ONTAP Select：

* ONTAP System Manager
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* 适用于 VMware vSphere 的 Virtual Storage Console


要确定受支持的客户端软件版本，请查看 link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]。如果客户端软件支持 ONTAP 9，则 ONTAP Select 也支持相同版本。


NOTE: 使用 SnapCenter 和相应的插件需要基于服务器的许可证。ONTAP Select 目前不支持 SnapCenter 插件的存储系统许可。

ONTAP Select 不支持列表中未包含的任何其他 NetApp 客户端软件。

.可能的配置选项
配置集群时，有多种选项可用，包括以下选项：

* 创建网络配置
* 规划您的聚合
* 创建数据存储 VM (SVM)


.购买了具有存储容量的许可证
如果您决定在部署 ONTAP Select 集群的过程中不安装具有存储容量的许可证文件，则必须在使用购买的许可证运行的集群的宽限期到期之前获取并安装许可证文件。

.镜像聚合
Deploy 管理实用程序从可用数据存储空间（如 Pool0 和 Pool1）在每个 ONTAP Select 节点上创建数据备用磁盘。要在多节点集群上实现数据的高可用性，必须使用这些备用磁盘创建镜像聚合。


NOTE: 只有将数据聚合配置为镜像聚合时才支持高可用性接管。
