---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 首先熟悉适用于 ONTAP Select 环境的一般网络概念。然后探索单节点和多节点集群的具体特征和可用选项。 
---
= ONTAP Select 网络概念和特征
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
首先熟悉适用于 ONTAP Select 环境的一般网络概念。然后探索单节点和多节点集群的具体特征和可用选项。



== 物理网络

物理网络主要通过提供底层第二层交换基础设施来支持 ONTAP Select 集群部署。与物理网络相关的配置包括虚拟机管理程序主机和更广泛的交换网络环境。



=== 主机 NIC 选项

每个 ONTAP Select 虚拟机监控程序主机必须配置两个或四个物理端口。您选择的确切配置取决于几个因素，包括：

* 集群是否包含一个或多个 ONTAP Select 主机
* 使用何种虚拟机管理程序操作系统
* 如何配置虚拟交换机
* 是否将 LACP 与链接一起使用




=== 物理交换机配置

您必须确保物理交换机的配置支持 ONTAP Select 部署。物理交换机与基于虚拟机管理程序的虚拟交换机集成。您选择的确切配置取决于几个因素。主要考虑因素包括：

* 您将如何保持内部和外部网络之间的分离？
* 您是否会在数据和管理网络之间保持分离？
* 如何配置第二层 VLAN？




== 逻辑网络

ONTAP Select 使用两个不同的逻辑网络，根据类型分离流量。具体而言，流量可以在集群内的主机之间流动，也可以流向存储客户端和集群外的其他机器。虚拟机管理程序管理的虚拟交换机有助于支持逻辑网络。



=== 内部网络

使用多节点集群部署，各个 ONTAP Select 节点使用隔离的"内部"网络进行通信。此网络未在 ONTAP Select 集群中的节点之外公开或可用。


NOTE: 内部网络仅存在于多节点集群中。

内部网络具有以下特点：

* 用于处理 ONTAP 集群内流量，包括：
+
** 集群
** 高可用性互连 (HA-IC)
** RAID 同步镜像 (RSM)


* 基于 VLAN 的单层二层网络
* 静态 IP 地址由 ONTAP Select 分配：
+
** 仅限 IPv4
** 未使用 DHCP
** 链路本地地址


* 默认情况下，MTU 大小为 9000 字节，可以在 7500-9000 范围内（含）进行调整




=== 外部网络

外部网络处理 ONTAP Select 集群的节点与外部存储客户端以及其他机器之间的流量。外部网络是每个集群部署的一部分，具有以下特点：

* 用于处理 ONTAP 流量，包括：
+
** 数据 (NFS、CIFS、iSCSI)
** 管理（集群和节点；可选 SVM）
** 集群间（可选）


* 可选地支持 VLAN：
+
** 数据端口组
** 管理端口组


* 根据管理员的配置选项分配的 IP 地址：
+
** IPv4 或 IPv6


* 默认情况下，MTU 大小为 1500 字节（可调整）


外部网络存在于各种规模的集群中。



== 虚拟机网络环境

虚拟机管理程序主机提供多种网络功能。

ONTAP Select 依赖于通过虚拟机公开的以下功能：

虚拟机端口:: 有几个端口可供 ONTAP Select 使用。它们是根据几个因素分配和使用的，包括集群的大小。
虚拟交换机:: 虚拟机监控程序环境中的虚拟交换机软件，无论是 vSwitch（VMware）还是 Open vSwitch（KVM），都会将虚拟机暴露的端口与物理以太网 NIC 端口连接起来。您必须根据您的环境为每个 ONTAP Select 主机配置 vSwitch。

