---
sidebar: sidebar 
permalink: reference_plan_ots_vnas.html 
keywords: plan, planning, vnas, vmware esxi, external storage 
summary: 您应该考虑与使用 VMware ESXi 相关的几个规划问题。 
---
= ONTAP Select 的 VMware ESXi 外部存储要求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select vNAS 是一种解决方案，允许 ONTAP Select 数据存储位于运行 ONTAP Select 虚拟机的 ESXi 虚拟机监控程序主机外部。这些远程数据存储可以通过 VMware vSAN 或通用外部存储阵列访问。



[[basic-requirements-and-restrictions]]
== 基本要求和限制

ONTAP Select vNAS 解决方案可以与任何规模的 ONTAP Select 集群一起使用。

所有相关存储组件，包括硬件、软件和功能要求，都必须符合 link:https://mysupport.netapp.com/matrix/["互操作性表工具"^] 中描述的要求。此外，ONTAP Select 支持 VMware Storage/SAN Compatibility 文档中描述的所有外部存储阵列，包括 iSCSI、NAS (NFSv3)、Fibre Channel 和 Fibre Channel over Ethernet。外部阵列支持受到 ONTAP Select 支持的 ESXi 版本的限制。

使用 ONTAP Select vNAS 部署群集时，支持以下 VMware 功能：

* VMotion
* 高可用性 (HA)
* 分布式资源调度程序 (DRS)



NOTE: 单节点和多节点 ONTAP Select 集群支持这些 VMware 功能。部署多节点集群时，应确保来自同一集群的两个或多个节点不在同一虚拟机监控程序主机上运行。

不支持以下 VMware 功能：

* 容错 (FT)
* 虚拟数据存储库 (VVOL)




[[configuration-requirements]]
== 配置要求

如果您计划在外部存储阵列（iSCSI、光纤通道、以太网光纤通道）上使用 VMFS 数据存储区，则必须在配置 ONTAP Select 以使用存储之前创建 VMFS 存储池。如果您使用 NFS 数据存储区，则无需创建单独的 VMFS 数据存储区。所有 vSAN 数据存储区必须在同一 ESXi 群集中定义。


CAUTION: 在配置主机或执行存储添加操作时，必须为 VMware vSAN 或外部存储阵列上的每个数据存储区提供容量限制。指定的容量必须在外部存储的允许存储限制范围内。如果未提供容量限制，或者在磁盘创建操作期间外部存储空间用尽，则会发生错误。



[[best-practices]]
== 最佳实践

查看 VMware 文档，并遵循为 ESXi 主机确定的适用最佳实践。此外：

* 为 ONTAP Select 网络和外部存储（使用 iSCSI 或 NFS 时的 VMware vSAN 和通用存储阵列流量）定义专用网络端口、带宽和 vSwitch 配置
* 配置容量选项以限制存储利用率（ONTAP Select 不能消耗外部 vNAS 数据存储的整个容量）
* 验证所有通用外部存储阵列是否都尽可能使用可用的冗余和 HA 功能

