---
sidebar: sidebar 
permalink: reference_plan_best_practices.html 
keywords: plan, planning, best practices, recommendations 
summary: 在规划 ONTAP Select 部署时，您应该考虑一些最佳做法。 
---
= ONTAP Select 部署最佳实践摘要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在规划 ONTAP Select 部署时，您应该考虑一些最佳做法。



== 存储

您应该考虑以下存储最佳实践。



=== 全闪存或通用闪存阵列

使用全闪存 VSAN 或通用闪存阵列的 ONTAP Select 虚拟 NAS (vNAS) 部署应遵循使用非 SSD DAS 存储的 ONTAP Select 最佳实践。



=== 外部存储

您应该遵守以下建议：

* 为 ONTAP Select 网络和外部存储定义专用网络端口、带宽和 vSwitch 配置
* 配置容量选项以限制存储利用率（ONTAP Select 不能消耗外部存储池的整个容量）
* 验证所有外部存储阵列是否都尽可能使用可用的冗余和 HA 功能




=== 虚拟机监控程序核心硬件

单个 ONTAP Select 聚合中的所有驱动器应为相同类型。例如，您不应该将 HDD 和 SSD 驱动器混合在一个聚合中。



=== RAID 控制器

服务器 RAID 控制器应配置为在写回模式下操作。如果发现写入工作负载性能问题，请检查控制器设置并确保未启用 writethrough 或 writearound。

如果物理服务器包含管理所有本地连接磁盘的单个 RAID 控制器，NetApp 建议为服务器操作系统创建单独的 LUN，并为 ONTAP Select 创建一个或多个 LUN。如果启动磁盘损坏，此最佳做法允许管理员重新创建 OS LUN，而不会影响 ONTAP Select。

RAID 控制器缓存用于存储所有传入的块更改，而不仅仅是针对 NVRAM 分区的更改。因此，在选择 RAID 控制器时，请选择具有最大可用缓存的控制器。较大的缓存可以减少磁盘刷新频率，并提高 ONTAP Select VM、虚拟机监控程序和服务器上任何并置计算 VM 的性能。



=== RAID 组

最佳 RAID 组大小为 8 到 12 个驱动器。每个 RAID 组的最大驱动器数量为 24 个。

每个 ONTAP Select 节点支持的 NVME 驱动器数上限为 14 个。

备用磁盘是可选的，但建议使用。NetApp 还建议为每个 RAID 组使用一个备用磁盘；但是，可以为所有 RAID 组使用全局备用磁盘。例如，您可以为每三个 RAID 组使用两个备用磁盘，每个 RAID 组由 8 到 12 个驱动器组成。

ONTAP Select 通过增加 RAID 组内的 LUN 数量不会获得性能优势。多个 LUN 只应用于遵循 SATA/NL-SAS 配置的最佳实践或绕过虚拟机监控程序文件系统限制。



=== VMware ESXi 主机

NetApp 建议使用 ESXi 8.0 或更高版本，并将 NVMe 磁盘用于托管系统磁盘的数据存储区。此配置可为 NVRAM 分区提供最佳性能。


NOTE: 在 ESXi 8.0 或更高版本上安装时，无论系统磁盘驻留在 SSD 还是 NVMe 磁盘上，ONTAP Select 都使用 vNVMEe 驱动程序。这会将 VM 硬件级别设置为 13，这与 ESXi 8.0 及更高版本兼容。

为 ONTAP Select 网络和外部存储（使用 iSCSI 或 NFS 时的 VMware vSAN 和通用存储阵列流量）定义专用网络端口、带宽和 vSwitch 配置。

配置容量选项以限制存储利用率（ONTAP Select 不能占用外部 vNAS 数据存储库的整个容量）。

确保所有通用外部存储阵列尽可能使用可用的冗余和 HA 功能。



=== VMware Storage vMotion

在决定是否将 VMware Storage vMotion 与 ONTAP Select 节点一起使用时，新主机上的可用容量不是唯一的因素。底层存储类型、主机配置和网络功能应能够承受与原始主机相同的工作负载。



== 网络连接

您应该考虑以下网络最佳实践。



=== 重复 MAC 地址

为了消除多个 Deploy 实例分配重复 MAC 地址的可能性，应使用每个第 2 层网络的一个 Deploy 实例来创建或管理 ONTAP Select 集群或节点。



=== EMS 消息

应仔细监控 ONTAP Select 双节点集群，以查看指示已禁用存储故障转移的 EMS 消息。这些消息表明与调解人服务的连接已断开，应立即予以纠正。



=== 节点之间的延迟

两个节点之间的网络必须支持 5 ms 的平均延迟和额外的 5 ms 周期性抖动。在部署集群之前，请使用 ONTAP Select 产品架构和最佳实践技术报告中描述的程序测试网络。



=== 负载平衡

要优化内部和外部 ONTAP Select 网络之间的负载平衡，请使用基于发起虚拟端口的路由负载平衡策略。



=== 多个第 2 层网络

如果数据流量跨越多个第 2 层网络，并且需要使用 VLAN 端口，或者使用多个 IPspace 时，则应使用 VGT。



=== 物理交换机配置

VMware 建议在连接到 ESXi 主机的交换机端口上将 STP 设置为 Portfast。未在交换机端口上将 STP 设置为 Portfast 可能会影响 ONTAP Select 容忍上行链路故障的能力。使用 LACP 时，LACP 计时器应设置为快速（1 秒）。负载均衡策略应设置为端口组上的基于 IP 哈希的路由，以及 LAG 上的源和目标 IP 地址以及 TCP/UDP 端口和 VLAN。



=== 适用于 KVM 的虚拟交换机选项

您必须在每个 ONTAP Select 主机上配置虚拟交换机，以支持外部网络和内部网络（仅限多节点集群）。作为部署多节点集群的一部分，您应该测试内部集群网络上的网络连接。

要了解有关如何在虚拟机监控程序主机上配置 Open vSwitch 的更多信息，请参见 link:https://www.netapp.com/media/13134-tr4613.pdf["ONTAP Select on KVM 产品架构和最佳实践"^] 技术报告。



== HA

对于高可用性，您应该考虑以下最佳实践。



=== 部署备份

最佳做法是定期备份 Deploy 配置数据，包括在创建集群之后。这对于双节点集群尤其重要，因为调解器配置数据包含在备份中。

创建或部署集群后，应执行以下操作link:task_cli_clusters.html["备份 ONTAP Select Deploy 配置数据"]。



=== 镜像聚合

虽然需要镜像聚合的存在来提供主聚合的最新（RPO 0）副本，但要注意主聚合的可用空间不会不足。主聚合中的低空间条件可能导致 ONTAP 删除用作存储回馈基准的通用 Snapshot 副本。其工作原理是为了适应客户端写入。但是，故障恢复时缺少通用 Snapshot 副本要求 ONTAP Select 节点从镜像聚合中执行完整的基线。在无共享环境中，此操作可能需要大量时间。


NOTE: NetApp 建议您为镜像聚合保持至少 20% 的可用空间，以获得最佳的存储性能和可用性。虽然对于非镜像聚合的建议为 10%，但文件系统可以使用额外的 10% 空间来吸收增量更改。由于 ONTAP 基于写时复制 Snapshot 的架构，增量更改会增加镜像聚合的空间利用率。如果不遵守这些最佳做法，可能会对性能产生负面影响。仅当数据聚合配置为镜像聚合时，才支持高可用性接管。



=== NIC 聚合、分组和故障转移

ONTAP Select 支持双节点集群的单个 10Gb 链路；但是，NetApp 最佳做法是通过在 ONTAP Select 集群的内部和外部网络上进行 NIC 聚合或 NIC 组合来实现硬件冗余。

如果 NIC 有多个专用集成电路（ASIC），则在通过 NIC 分组为内部和外部网络构建网络结构时，从每个 ASIC 中选择一个网络端口。

NetApp 建议 LACP 模式在 ESXi 和物理交换机上都处于活动状态。此外，LACP 计时器应在物理交换机、端口、端口通道接口和 VMNIC 上设置为 fast（1 秒）。

使用分布式 vSwitch 与 LACP 时，NetApp 建议您将负载平衡策略配置为基于端口组上的 IP 哈希、源和目标 IP 地址、TCP/UDP 端口以及 LAG 上的 VLAN 的路由。



=== 双节点拉伸 HA（MetroCluster SDS）最佳实践

在创建 MetroCluster SDS 之前，请使用 ONTAP Deploy 连接检查器，以确保两个数据中心之间的网络延迟在可接受的范围内。

使用虚拟访客标记 (VGT) 和双节点集群时有一个额外的警告。在双节点集群配置中，节点管理 IP 地址用于在 ONTAP 完全可用之前与中介建立早期连接。因此，映射到节点管理 LIF（端口 e0a）的端口组仅支持外部交换机标记 (EST) 和虚拟交换机标记 (VST) 标记。此外，如果管理和数据流量都使用相同的端口组，则整个双节点集群仅支持 EST 和 VST。
