---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 您可以使用命令行界面就地升级现有 Deploy 实用程序虚拟机。 
---
= 升级 ONTAP Select Deploy 实例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 ONTAP Select Deploy 实用程序 CLI 就地升级现有 ONTAP Select Deploy 实用程序虚拟机。

您可以从 ONTAP Select Deploy 9.17.1 或 9.16.1 直接升级到 ONTAP Select Deploy 9.18.1。要从早期版本升级，例如 ONTAP Select Deploy 9.15.1，您必须首先升级到 ONTAP Select Deploy 9.16.1 或 9.17.1，然后升级到 ONTAP Select Deploy 9.18.1。

[NOTE]
====
如果您安装了较旧的 ONTAP Select Deploy 管理实用程序实例，则应升级到当前版本。ONTAP Select 节点和 ONTAP Select Deploy 组件独立升级。有关更多详细信息，请参阅 link:concept_adm_upgrading_nodes.html["升级 ONTAP Select 节点"^]。

====
.开始之前
验证 ONTAP Select Deploy 在升级期间未用于执行任何其他任务。



== 步骤 1：下载升级包

要开始升级过程，请从 NetApp 支持站点下载 ONTAP Select Deploy 升级文件。升级包的格式为单个压缩文件。

.步骤
. 访问 link:https://mysupport.netapp.com/site/downloads/["NetApp 支持站点下载"^] 页面。
. 向下滚动并选择 *ONTAP Select Deploy*。
. 选择所需的 ONTAP Select 版本。
. 查看最终用户许可协议 (EULA) 并选择 *Accept & Continue*。
. 选择并下载相应的 *ONTAP Select Deploy Upgrade* 软件包。根据需要回复所有提示。




== 步骤 2：将包上载到 ONTAP Select Deploy 虚拟机

下载包后，需要将文件上传到 ONTAP Select Deploy 虚拟机。

.关于此任务
此任务描述了一种将文件上传到 ONTAP Select Deploy 虚拟机的方法。可能还有其他更适合您环境的选项。

.开始之前
* 确认升级文件在本地工作站上可用。
* 确认您拥有管理员用户帐户的密码。


.步骤
. 在本地工作站上的命令外壳中，使用 `scp`（Secure Copy Protocol）实用程序将映像文件上传到 ONTAP Select Deploy 虚拟机，如以下示例所示：
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.结果
升级文件存储在管理员用户的主目录中。



== 步骤 3：应用升级包

将升级文件上传到 ONTAP Select Deploy 虚拟机后，可以应用升级。

.开始之前
* 验证升级文件已放置在 ONTAP Select Deploy 实用程序虚拟机的哪个目录中。
* 确认在执行升级时，ONTAP Select Deploy 不用于执行任何其他任务。


.步骤
. 使用管理员帐户通过 SSH Sign in 到 ONTAP Select Deploy 实用程序 CLI。
. 使用适当的目录路径和文件名执行升级：
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
示例命令：

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完成后
在升级过程完成之前，将要求您创建 ONTAP Select Deploy 虚拟机配置的备份。此外，应清除浏览器缓存，以便查看新创建的 ONTAP Select Deploy 页面。
