---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果 ONTAP Select Deploy 实用程序因某种原因失败或不可用，您将失去管理 ONTAP Select 节点和群集的功能。此外，由于 Deploy 中包含的中介服务不可用，所有双节点群集都将失去 HA 功能。如果发生不可恢复的故障，则必须恢复 Deploy 实用程序实例以还原管理和 HA 功能。 
---
= 恢复双节点集群的 ONTAP Select Deploy 实用程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果 ONTAP Select Deploy 实用程序因某种原因失败或不可用，您将失去管理 ONTAP Select 节点和群集的功能。此外，由于 Deploy 中包含的中介服务不可用，所有双节点群集都将失去 HA 功能。如果发生不可恢复的故障，则必须恢复 Deploy 实用程序实例以还原管理和 HA 功能。



[[prepare-to-recover-the-deploy-utility]]
== 准备恢复 Deploy 实用程序

在尝试恢复 Deploy 实用程序的实例以确保成功之前，需要做好准备。您必须熟悉几种管理程序，并拥有所需的信息。

.步骤
. 验证是否可以在虚拟机管理程序环境中安装 ONTAP Select Deploy 实用程序的新实例。
+
link:task_install_deploy.html["了解有关安装 ONTAP Select Deploy 实用程序的信息"]

. 验证是否可以登录到 ONTAP Select 集群并访问 ONTAP 集群 shell (CLI)。
. 确定是否从包含 ONTAP Select 双节点集群的失败 Deploy 实用程序实例中备份了配置数据。您可能有一个不包含集群的备份。
. 验证是否可以还原 Deploy 配置数据的备份，具体视使用的恢复过程而定。
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["了解有关将 Deploy 配置数据还原到新虚拟机的信息"]

. 您拥有失败的原始 Deploy 实用工具虚拟机的 IP 地址。
. 确定是使用 Capacity Pools 还是 Capacity Tiers 许可。如果使用 Capacity Pools 许可，则必须在恢复或还原 Deploy 实例后重新安装每个 Capacity Pool 许可证。
. 决定在恢复 ONTAP Select Deploy 实用程序的实例时使用哪个过程。您的决定取决于您是否有来自包含 ONTAP Select 双节点集群的原始失败 Deploy 实用程序的配置数据的备份。
+
[cols="35,65"]
|===
| 您是否有包含双节点集群的 Deploy 备份？ | 使用恢复过程... 


| 是 | <<restore-deploy-backup,使用配置备份还原 Deploy 实用程序实例>> 


| 否 | <<restore-and-recover-deploy,重新配置和恢复 Deploy 实用程序实例>> 
|===




[[restore-a-deploy-utility-instance-using-a-configuration-backup]]
[[restore-deploy-backup]]
== 使用配置备份还原 Deploy 实用程序实例

如果有包含双节点群集的失败 Deploy 实用程序实例的备份，则可以将配置数据还原到新的 Deploy 虚拟机实例。然后，您必须通过对 ONTAP Select 群集中的两个节点执行其他配置来完成恢复。

.开始之前
从包含双节点集群的原始失败 Deploy 虚拟机备份配置数据。您必须能够登录到双节点集群的 ONTAP CLI 并知道两个节点的 ONTAP 名称。

.关于此任务
由于还原的配置备份包含双节点群集，因此会在新的 Deploy 实用程序虚拟机中重新创建中介 iSCSI 目标和邮箱。

.步骤
. 准备 ONTAP Select Deploy 实用程序的新实例：
+
.. 安装新的 Deploy 实用工具虚拟机。
.. 将 Deploy 配置从以前的备份还原到新虚拟机。
+
有关安装和还原过程的详细信息，请参见相关任务。



. Sign in 到 ONTAP Select 双节点集群的 ONTAP 命令行界面。
. 进入高级权限模式：
+
[source, cli]
----
set adv
----
. 如果新 Deploy 虚拟机的 IP 地址与原始 Deploy 虚拟机不同，请删除旧的调解器 iSCSI 目标并添加新目标：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
该 `<ip_address>` 参数是新 Deploy 虚拟机的 IP 地址。

+
这些命令允许 ONTAP Select 节点发现新 Deploy 实用程序虚拟机上的邮箱磁盘。

. 确定调解器磁盘的名称：
+
[source, cli]
----
disk show -container-type mediator
----
. 向两个节点分配邮箱磁盘：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 确认已启用存储故障转移：
+
[source, cli]
----
storage failover show
----


.完成后
如果使用 Capacity Pools 许可，请重新安装每个 Capacity Pool 许可证。有关其他详细信息，请参见 link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安装容量池许可证"]。



[[reconfigure-and-recover-a-deploy-utility-instance]]
[[restore-and-recover-deploy]]
== 重新配置和恢复 Deploy 实用程序实例

如果没有包含双节点群集的失败 Deploy 实用程序实例的备份，请在新 Deploy 虚拟机中配置调解器 iSCSI 目标和邮箱。然后，通过对 ONTAP Select 群集中的两个节点执行其他配置来完成恢复。

.开始之前
验证您是否具有新部署实用程序实例的介体目标的名称。您必须能够 Sign in 到双节点群集的 ONTAP CLI，并知道两个节点的 ONTAP 名称。

.关于此任务
您可以选择将配置备份还原到新的 Deploy 虚拟机，即使它不包含双节点集群。由于双节点集群不会随还原一起重新创建，因此您必须通过 Deploy 中的 ONTAP Select 在线文档网页将中介 iSCSI 目标和邮箱手动添加到新的 Deploy 实用程序实例。您必须能够 sign in 到双节点集群，并知道这两个节点的 ONTAP 名称。


NOTE: 恢复过程的目标是将双节点群集恢复到正常状态，在此状态下可以执行正常的 HA 接管和交还操作。

.步骤
. 准备 ONTAP Select Deploy 实用程序的新实例：
+
.. 安装新的 Deploy 实用工具虚拟机。
.. （可选）将 Deploy 配置从以前的备份还原到新虚拟机。
+
如果还原以前的备份，新 Deploy 实例将不包含双节点集群。有关安装和还原过程的更多详细信息，请参见相关信息部分。



. Sign in 到 ONTAP Select 双节点集群的 ONTAP 命令行界面。
. 进入高级特权模式：
+
[source, cli]
----
set adv
----
. 获取介体 iSCSI 目标名称：
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 访问新 Deploy 实用程序虚拟机上的在线文档网页并使用管理员帐户 sign in：
+
`\http://<ip_address>/api/ui`

+
必须使用 Deploy 虚拟机的 IP 地址。

. 选择 *Mediator*，然后选择 *GET /mediators*。
. 选择 *Try it out!* 以显示由 Deploy 维护的调解员列表。
+
注意所需调解人实例的 ID。

. 选择 *Mediator*，然后选择 *POST*。
. 请提供 mediator_id 的值。
. 选择  `iscsi_target` 旁边的 *Model* 并填写名称值。
+
使用目标名称作为 iqn_name 参数。

. 选择 *Try it out!* 以创建介体 iSCSI 目标。
+
如果请求成功，您将收到 HTTP 状态代码 200。

. 如果新 Deploy 虚拟机的 IP 地址与原始 Deploy 虚拟机不同，则必须使用 ONTAP CLI 删除旧的调解器 iSCSI 目标并添加新目标：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
该 `<ip_address>` 参数是新 Deploy 虚拟机的 IP 地址。

+
这些命令允许 ONTAP Select 节点发现新 Deploy 实用程序虚拟机上的邮箱磁盘。

. 确定调解器磁盘的名称：
+
[source, cli]
----
disk show -container-type mediator
----
. 向两个节点分配邮箱磁盘：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 确认已启用存储故障转移：
+
[source, cli]
----
storage failover show
----


.完成后
如果使用 Capacity Pools 许可，请重新安装每个 Capacity Pool 许可证。有关其他详细信息，请参见 link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安装容量池许可证"]。
